version: '3.8'

services:
  stealthguardian-middleware:
    image: stealthguardian-middleware:latest
    restart: "no"
    build:
      dockerfile: ./middleware/middleware.Dockerfile
    env_file:
      - .env
    ports:
      - "45134:8000/tcp"
    healthcheck:
      test: curl --fail http://localhost:45134/ || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - ./middleware/API:/API:ro
      - ./middleware/database:/database
      - ./middleware/scripts:/scripts:ro
      - ./ssl:/ssl:ro
      - ./agent/:/agent:ro
    networks:
      - stealthguardian

  stealthguardian-cs-integration:
    image: stealthguardian-cs-integration:latest
    restart: "no"
    build:
      dockerfile: ./integration/cobaltstrike/cobaltstrike.Dockerfile
    env_file:
      - .env
    volumes:
      - ./integration/cobaltstrike:/cobaltstrike
      - ${CobaltStrike_Directory}:/cobaltstrike/cobaltstrike
    networks:
      - stealthguardian
    deploy:
      replicas: ${UseCobaltStrike}

networks:
  stealthguardian:
    name: stealthguardian_net
